server:
  port: 8085

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/orderservicedb
    username: root
    password: S@ranyaSql23
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

